# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalcontainer import Huishoudelijkafvalcontainer

class TestHuishoudelijkafvalcontainer(unittest.TestCase):
    """Huishoudelijkafvalcontainer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Huishoudelijkafvalcontainer:
        """Test Huishoudelijkafvalcontainer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Huishoudelijkafvalcontainer`
        """
        model = Huishoudelijkafvalcontainer()
        if include_optional:
            return Huishoudelijkafvalcontainer(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_container_links.HuishoudelijkafvaldefaultContainerLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainer_link.HuishoudelijkafvalcontainerLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    cluster = huishoudelijkafval_api_client.models.huishoudelijkafvalcluster_link.HuishoudelijkafvalclusterLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    locatie = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainerlocatie_link.HuishoudelijkafvalcontainerlocatieLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    type = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainertype_link.HuishoudelijkafvalcontainertypeLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    bag_hoofdadres_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                id_nummer = '',
                serienummer = '',
                cluster_id = '',
                eigenaar_id = '',
                eigenaar_naam = '',
                status = -9223372036854775808,
                fractie_code = '',
                fractie_omschrijving = '',
                datum_creatie = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_plaatsing = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_operationeel = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_aflopen_garantie = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_oplevering = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verwijderd_dp = True,
                geadopteerd_ind = True,
                locatie_id = '',
                geometrie = huishoudelijkafval_api_client.models.point.Point(),
                type_id = '',
                bag_hoofdadres_verblijfsobject_id = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_nummeraanduiding_id = '',
                container_ral_kleur_naam = '',
                container_ral_kleur_code = '',
                container_ral_kleur_hexcode = '',
                container_chip_nummber = '',
                container_unit_card_lezer_id = '',
                container_kleur = '',
                container_mark = -9223372036854775808,
                container_datum_vervanging = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                container_datum_wijziging = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                container_end_of_life = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                container_eigenaarschap = '',
                container_eigenaarschap_opmerking = '',
                container_opmerking = ''
            )
        else:
            return Huishoudelijkafvalcontainer(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_container_links.HuishoudelijkafvaldefaultContainerLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainer_link.HuishoudelijkafvalcontainerLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    cluster = huishoudelijkafval_api_client.models.huishoudelijkafvalcluster_link.HuishoudelijkafvalclusterLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    locatie = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainerlocatie_link.HuishoudelijkafvalcontainerlocatieLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    type = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainertype_link.HuishoudelijkafvalcontainertypeLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    bag_hoofdadres_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                cluster_id = '',
                locatie_id = '',
                type_id = '',
                bag_hoofdadres_verblijfsobject_id = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_nummeraanduiding_id = '',
        )
        """

    def testHuishoudelijkafvalcontainer(self):
        """Test Huishoudelijkafvalcontainer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
