# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_loopafstand_categorie_v2_links import HuishoudelijkafvaldefaultLoopafstandCategorieV2Links

class TestHuishoudelijkafvaldefaultLoopafstandCategorieV2Links(unittest.TestCase):
    """HuishoudelijkafvaldefaultLoopafstandCategorieV2Links unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HuishoudelijkafvaldefaultLoopafstandCategorieV2Links:
        """Test HuishoudelijkafvaldefaultLoopafstandCategorieV2Links
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HuishoudelijkafvaldefaultLoopafstandCategorieV2Links`
        """
        model = HuishoudelijkafvaldefaultLoopafstandCategorieV2Links()
        if include_optional:
            return HuishoudelijkafvaldefaultLoopafstandCategorieV2Links(
                var_schema = '',
                var_self = huishoudelijkafval_api_client.models.huishoudelijkafvalloopafstand_categorie_v2_link.Huishoudelijkafvalloopafstand_categorie_v2Link(
                    href = '', 
                    title = '', 
                    id = '', )
            )
        else:
            return HuishoudelijkafvaldefaultLoopafstandCategorieV2Links(
                var_schema = '',
                var_self = huishoudelijkafval_api_client.models.huishoudelijkafvalloopafstand_categorie_v2_link.Huishoudelijkafvalloopafstand_categorie_v2Link(
                    href = '', 
                    title = '', 
                    id = '', ),
        )
        """

    def testHuishoudelijkafvaldefaultLoopafstandCategorieV2Links(self):
        """Test HuishoudelijkafvaldefaultLoopafstandCategorieV2Links"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
