# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalweging_list_embedded import PaginatedHuishoudelijkafvalwegingListEmbedded

class TestPaginatedHuishoudelijkafvalwegingListEmbedded(unittest.TestCase):
    """PaginatedHuishoudelijkafvalwegingListEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalwegingListEmbedded:
        """Test PaginatedHuishoudelijkafvalwegingListEmbedded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalwegingListEmbedded`
        """
        model = PaginatedHuishoudelijkafvalwegingListEmbedded()
        if include_optional:
            return PaginatedHuishoudelijkafvalwegingListEmbedded(
                weging = [
                    huishoudelijkafval_api_client.models.huishoudelijkafvalweging.Huishoudelijkafvalweging(
                        _links = null, 
                        id = '', 
                        cluster_id = '', 
                        cluster_subcluster_indicatie = True, 
                        weegsysteem_id = -9223372036854775808, 
                        weegsysteem_omschrijving = '', 
                        volgnummer = -9223372036854775808, 
                        datum_weging = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        tijdstip_weging = '', 
                        locatienummer = '', 
                        fractie_code = -9223372036854775808, 
                        fractie_omschrijving = '', 
                        eerste_weging = 1.337, 
                        tweede_weging = 1.337, 
                        netto_gewicht = 1.337, 
                        geometrie = huishoudelijkafval_api_client.models.point.Point(), 
                        bediening_code = -9223372036854775808, 
                        bediening_omschrijving = '', 
                        wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        verwijderd_dp = True, 
                        bag_hoofdadres_verblijfsobject_id = '', 
                        gbd_buurt_id = '', 
                        bag_openbareruimte_id = '', 
                        bag_nummeraanduiding_id = '', 
                        weging_kenteken = '', )
                    ]
            )
        else:
            return PaginatedHuishoudelijkafvalwegingListEmbedded(
        )
        """

    def testPaginatedHuishoudelijkafvalwegingListEmbedded(self):
        """Test PaginatedHuishoudelijkafvalwegingListEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
