# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalbag_object_loopafstand_v2 import HuishoudelijkafvalbagObjectLoopafstandV2

class TestHuishoudelijkafvalbagObjectLoopafstandV2(unittest.TestCase):
    """HuishoudelijkafvalbagObjectLoopafstandV2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HuishoudelijkafvalbagObjectLoopafstandV2:
        """Test HuishoudelijkafvalbagObjectLoopafstandV2
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HuishoudelijkafvalbagObjectLoopafstandV2`
        """
        model = HuishoudelijkafvalbagObjectLoopafstandV2()
        if include_optional:
            return HuishoudelijkafvalbagObjectLoopafstandV2(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_bag_object_loopafstand_v2_links.HuishoudelijkafvaldefaultBagObjectLoopafstandV2Links(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalbag_object_loopafstand_v2_link.Huishoudelijkafvalbag_object_loopafstand_v2Link(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    cluster = huishoudelijkafval_api_client.models.huishoudelijkafvalcluster_link.HuishoudelijkafvalclusterLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    loopafstand_categorie = huishoudelijkafval_api_client.models.huishoudelijkafvalloopafstand_categorie_v2_link.Huishoudelijkafvalloopafstand_categorie_v2Link(
                        href = '', 
                        title = '', 
                        id = '', ), ),
                id = '',
                bag_object_id = '',
                bag_object_type = '',
                cluster_id = '',
                fractie = '',
                fractie_omschrijving = '',
                loopafstand_categorie_id = '',
                loopafstand = 1.337,
                geometrie = huishoudelijkafval_api_client.models.polygon.Polygon(),
                wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verwijderd_dp = True
            )
        else:
            return HuishoudelijkafvalbagObjectLoopafstandV2(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_bag_object_loopafstand_v2_links.HuishoudelijkafvaldefaultBagObjectLoopafstandV2Links(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalbag_object_loopafstand_v2_link.Huishoudelijkafvalbag_object_loopafstand_v2Link(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    cluster = huishoudelijkafval_api_client.models.huishoudelijkafvalcluster_link.HuishoudelijkafvalclusterLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    loopafstand_categorie = huishoudelijkafval_api_client.models.huishoudelijkafvalloopafstand_categorie_v2_link.Huishoudelijkafvalloopafstand_categorie_v2Link(
                        href = '', 
                        title = '', 
                        id = '', ), ),
                id = '',
                cluster_id = '',
                loopafstand_categorie_id = '',
        )
        """

    def testHuishoudelijkafvalbagObjectLoopafstandV2(self):
        """Test HuishoudelijkafvalbagObjectLoopafstandV2"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
