# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalafvoermomenten_list import PaginatedHuishoudelijkafvalafvoermomentenList

class TestPaginatedHuishoudelijkafvalafvoermomentenList(unittest.TestCase):
    """PaginatedHuishoudelijkafvalafvoermomentenList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalafvoermomentenList:
        """Test PaginatedHuishoudelijkafvalafvoermomentenList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalafvoermomentenList`
        """
        model = PaginatedHuishoudelijkafvalafvoermomentenList()
        if include_optional:
            return PaginatedHuishoudelijkafvalafvoermomentenList(
                page = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list_page.PaginatedHuishoudelijkafvaladres_loopafstand_v2List_page(
                    number = 3, 
                    size = 20, 
                    total_elements = 5, 
                    total_pages = 3, ),
                links = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links(
                    self = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_self.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_self(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3', ), 
                    next = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_next.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_next(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=4', ), 
                    previous = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_previous.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_previous(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=2', ), ),
                embedded = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalafvoermomenten_list__embedded.PaginatedHuishoudelijkafvalafvoermomentenList__embedded(
                    afvoermomenten = [
                        huishoudelijkafval_api_client.models.huishoudelijkafvalafvoermomenten.Huishoudelijkafvalafvoermomenten(
                            _links = null, 
                            id = '', 
                            verwerker = '', 
                            bon_nummer = '', 
                            datum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            tijd = '', 
                            ontvangst_locatie = '', 
                            afvalstroom_nummer = '', 
                            aanbieder = '', 
                            aanbieder_standplaats = '', 
                            aanbieder_standplaats_omschrijving = '', 
                            aanbieder_adres = '', 
                            aanbieder_postcode = '', 
                            aanbieder_plaatsnaam = '', 
                            afval_soort = '', 
                            geaccepteerd = '', 
                            opmerking = '', 
                            kenteken = '', 
                            kenteken_kort = '', 
                            weeg_bon = '', 
                            weeg_datum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            weeg_tijdstip = '', 
                            inweging = -9223372036854775808, 
                            uitweging = -9223372036854775808, 
                            netto_gewicht = '', 
                            afvalstof_code = '', 
                            afvalstof_omschrijving = '', )
                        ], )
            )
        else:
            return PaginatedHuishoudelijkafvalafvoermomentenList(
        )
        """

    def testPaginatedHuishoudelijkafvalafvoermomentenList(self):
        """Test PaginatedHuishoudelijkafvalafvoermomentenList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
