# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalcontainerlocatie import Huishoudelijkafvalcontainerlocatie

class TestHuishoudelijkafvalcontainerlocatie(unittest.TestCase):
    """Huishoudelijkafvalcontainerlocatie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Huishoudelijkafvalcontainerlocatie:
        """Test Huishoudelijkafvalcontainerlocatie
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Huishoudelijkafvalcontainerlocatie`
        """
        model = Huishoudelijkafvalcontainerlocatie()
        if include_optional:
            return Huishoudelijkafvalcontainerlocatie(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_containerlocatie_links.HuishoudelijkafvaldefaultContainerlocatieLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainerlocatie_link.HuishoudelijkafvalcontainerlocatieLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    bag_hoofdadres_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                serienummer = '',
                status = -9223372036854775808,
                geometrie = huishoudelijkafval_api_client.models.point.Point(),
                eigenaar_id = '',
                eigenaar_naam = '',
                datum_creatie = '',
                datum_plaatsing = '',
                datum_operationeel = '',
                datum_oplevering = '',
                wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verwijderd_dp = True,
                datum_einde_garantie = '',
                ind_bevat_container = True,
                bag_hoofdadres_verblijfsobject_id = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_nummeraanduiding_id = '',
                containerlocatie_type_naam = '',
                containerlocatie_id_nummer = '',
                containerlocatie_datum_wijziging = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                containerlocatie_opmerking = '',
                containerlocatie_end_of_life = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                containerlocatie_eigenaarschap = '',
                containerlocatie_eigenaarschap_opmerking = '',
                containerlocatie_type_artikelcode = '',
                bronadres = ''
            )
        else:
            return Huishoudelijkafvalcontainerlocatie(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_containerlocatie_links.HuishoudelijkafvaldefaultContainerlocatieLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainerlocatie_link.HuishoudelijkafvalcontainerlocatieLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    bag_hoofdadres_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                bag_hoofdadres_verblijfsobject_id = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_nummeraanduiding_id = '',
        )
        """

    def testHuishoudelijkafvalcontainerlocatie(self):
        """Test Huishoudelijkafvalcontainerlocatie"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
