# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalcluster_list_embedded import PaginatedHuishoudelijkafvalclusterListEmbedded

class TestPaginatedHuishoudelijkafvalclusterListEmbedded(unittest.TestCase):
    """PaginatedHuishoudelijkafvalclusterListEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalclusterListEmbedded:
        """Test PaginatedHuishoudelijkafvalclusterListEmbedded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalclusterListEmbedded`
        """
        model = PaginatedHuishoudelijkafvalclusterListEmbedded()
        if include_optional:
            return PaginatedHuishoudelijkafvalclusterListEmbedded(
                cluster = [
                    huishoudelijkafval_api_client.models.huishoudelijkafvalcluster.Huishoudelijkafvalcluster(
                        _links = null, 
                        id = '', 
                        subcluster_indicatie = True, 
                        geometrie = huishoudelijkafval_api_client.models.point.Point(), 
                        datum_opvoer = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        datum_ontstaan = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        datum_einde = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        verwijderd_dp = True, 
                        status = -9223372036854775808, 
                        bag_hoofdadres_verblijfsobject_id = '', 
                        gbd_buurt_id = '', 
                        bag_openbareruimte_id = '', 
                        bag_nummeraanduiding_id = '', 
                        bronadres = '', 
                        opmerking = '', )
                    ]
            )
        else:
            return PaginatedHuishoudelijkafvalclusterListEmbedded(
        )
        """

    def testPaginatedHuishoudelijkafvalclusterListEmbedded(self):
        """Test PaginatedHuishoudelijkafvalclusterListEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
