# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalservicegebieden_locatie_link import HuishoudelijkafvalservicegebiedenLocatieLink

class TestHuishoudelijkafvalservicegebiedenLocatieLink(unittest.TestCase):
    """HuishoudelijkafvalservicegebiedenLocatieLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HuishoudelijkafvalservicegebiedenLocatieLink:
        """Test HuishoudelijkafvalservicegebiedenLocatieLink
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HuishoudelijkafvalservicegebiedenLocatieLink`
        """
        model = HuishoudelijkafvalservicegebiedenLocatieLink()
        if include_optional:
            return HuishoudelijkafvalservicegebiedenLocatieLink(
                href = '',
                title = '',
                id = ''
            )
        else:
            return HuishoudelijkafvalservicegebiedenLocatieLink(
                href = '',
                title = '',
                id = '',
        )
        """

    def testHuishoudelijkafvalservicegebiedenLocatieLink(self):
        """Test HuishoudelijkafvalservicegebiedenLocatieLink"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
