# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalcluster import Huishoudelijkafvalcluster

class TestHuishoudelijkafvalcluster(unittest.TestCase):
    """Huishoudelijkafvalcluster unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Huishoudelijkafvalcluster:
        """Test Huishoudelijkafvalcluster
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Huishoudelijkafvalcluster`
        """
        model = Huishoudelijkafvalcluster()
        if include_optional:
            return Huishoudelijkafvalcluster(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_cluster_links.HuishoudelijkafvaldefaultClusterLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalcluster_link.HuishoudelijkafvalclusterLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    bag_hoofdadres_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                subcluster_indicatie = True,
                geometrie = huishoudelijkafval_api_client.models.point.Point(),
                datum_opvoer = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_ontstaan = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                datum_einde = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verwijderd_dp = True,
                status = -9223372036854775808,
                bag_hoofdadres_verblijfsobject_id = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_nummeraanduiding_id = '',
                bronadres = '',
                opmerking = ''
            )
        else:
            return Huishoudelijkafvalcluster(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_cluster_links.HuishoudelijkafvaldefaultClusterLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalcluster_link.HuishoudelijkafvalclusterLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    bag_hoofdadres_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                bag_hoofdadres_verblijfsobject_id = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_nummeraanduiding_id = '',
        )
        """

    def testHuishoudelijkafvalcluster(self):
        """Test Huishoudelijkafvalcluster"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
