# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.gebieden_ggwgebieden_raw_identifier import GebiedenGgwgebiedenRawIdentifier

class TestGebiedenGgwgebiedenRawIdentifier(unittest.TestCase):
    """GebiedenGgwgebiedenRawIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GebiedenGgwgebiedenRawIdentifier:
        """Test GebiedenGgwgebiedenRawIdentifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GebiedenGgwgebiedenRawIdentifier`
        """
        model = GebiedenGgwgebiedenRawIdentifier()
        if include_optional:
            return GebiedenGgwgebiedenRawIdentifier(
                href = '',
                title = '',
                identificatie = ''
            )
        else:
            return GebiedenGgwgebiedenRawIdentifier(
                href = '',
                title = '',
                identificatie = '',
        )
        """

    def testGebiedenGgwgebiedenRawIdentifier(self):
        """Test GebiedenGgwgebiedenRawIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
