# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list_embedded import PaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded

class TestPaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded(unittest.TestCase):
    """PaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded:
        """Test PaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded`
        """
        model = PaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded()
        if include_optional:
            return PaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded(
                adres_loopafstand_v2 = [
                    huishoudelijkafval_api_client.models.huishoudelijkafvaladres_loopafstand_v2.Huishoudelijkafvaladres_loopafstand_v2(
                        _links = null, 
                        id = '', 
                        adresseerbaarobject_id = '', 
                        adresseerbaarobject_type = '', 
                        nummeraanduiding_id = '', 
                        gebruiksdoel = '', 
                        cluster_id = '', 
                        fractie = '', 
                        fractie_omschrijving = '', 
                        loopafstand_categorie_id = '', 
                        loopafstand = 1.337, 
                        geometrie = huishoudelijkafval_api_client.models.point.Point(), 
                        wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        verwijderd_dp = True, )
                    ]
            )
        else:
            return PaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded(
        )
        """

    def testPaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded(self):
        """Test PaginatedHuishoudelijkafvaladresLoopafstandV2ListEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
