# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalbijplaatsingen import Huishoudelijkafvalbijplaatsingen

class TestHuishoudelijkafvalbijplaatsingen(unittest.TestCase):
    """Huishoudelijkafvalbijplaatsingen unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Huishoudelijkafvalbijplaatsingen:
        """Test Huishoudelijkafvalbijplaatsingen
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Huishoudelijkafvalbijplaatsingen`
        """
        model = Huishoudelijkafvalbijplaatsingen()
        if include_optional:
            return Huishoudelijkafvalbijplaatsingen(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_bijplaatsingen_links.HuishoudelijkafvaldefaultBijplaatsingenLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalbijplaatsingen_link.HuishoudelijkafvalbijplaatsingenLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    cluster = huishoudelijkafval_api_client.models.huishoudelijkafvalcluster_link.HuishoudelijkafvalclusterLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_woonplaats = huishoudelijkafval_api_client.models.bag_woonplaatsen_raw_identifier.BagWoonplaatsenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                datum_waarneming = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                tijd_waarneming = '',
                cluster_id = '',
                gbd_buurt_code = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_verblijfsobject_id = '',
                bag_nummeraanduiding_id = '',
                bag_woonplaats_id = '',
                geometrie = huishoudelijkafval_api_client.models.point.Point(),
                bruingoed = True,
                containervies = True,
                crow_score = '',
                glas = True,
                glasgestremd = True,
                glastoegankelijk = True,
                glasvol = True,
                grof = True,
                handhaving = True,
                waarde_handhaving = '',
                huisvuil = True,
                karton = True,
                overig = True,
                papiervol = True,
                papiergestremd = True,
                papiertoegankelijk = True,
                restgestremd = True,
                resttoegankelijk = True,
                restvol = True,
                veegvuil = True,
                zwerfafval = True,
                waarnemer_rol = '',
                gbd_stadsdeel_naam = '',
                postcode = '',
                straatnaam = '',
                locatie_waarnemer = '',
                type_waarneming = '',
                grofvuildagen = '',
                adres_type = '',
                dumpplek = True,
                melding_door_collega_doorgezet = '',
                naam_melding_doorgezet = '',
                gebruikers_rol = ''
            )
        else:
            return Huishoudelijkafvalbijplaatsingen(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_bijplaatsingen_links.HuishoudelijkafvaldefaultBijplaatsingenLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalbijplaatsingen_link.HuishoudelijkafvalbijplaatsingenLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    cluster = huishoudelijkafval_api_client.models.huishoudelijkafvalcluster_link.HuishoudelijkafvalclusterLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_woonplaats = huishoudelijkafval_api_client.models.bag_woonplaatsen_raw_identifier.BagWoonplaatsenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                cluster_id = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_verblijfsobject_id = '',
                bag_nummeraanduiding_id = '',
                bag_woonplaats_id = '',
        )
        """

    def testHuishoudelijkafvalbijplaatsingen(self):
        """Test Huishoudelijkafvalbijplaatsingen"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
