# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalcontainerlocatie_list_embedded import PaginatedHuishoudelijkafvalcontainerlocatieListEmbedded

class TestPaginatedHuishoudelijkafvalcontainerlocatieListEmbedded(unittest.TestCase):
    """PaginatedHuishoudelijkafvalcontainerlocatieListEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalcontainerlocatieListEmbedded:
        """Test PaginatedHuishoudelijkafvalcontainerlocatieListEmbedded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalcontainerlocatieListEmbedded`
        """
        model = PaginatedHuishoudelijkafvalcontainerlocatieListEmbedded()
        if include_optional:
            return PaginatedHuishoudelijkafvalcontainerlocatieListEmbedded(
                containerlocatie = [
                    huishoudelijkafval_api_client.models.huishoudelijkafvalcontainerlocatie.Huishoudelijkafvalcontainerlocatie(
                        _links = null, 
                        id = '', 
                        serienummer = '', 
                        status = -9223372036854775808, 
                        geometrie = huishoudelijkafval_api_client.models.point.Point(), 
                        eigenaar_id = '', 
                        eigenaar_naam = '', 
                        datum_creatie = '', 
                        datum_plaatsing = '', 
                        datum_operationeel = '', 
                        datum_oplevering = '', 
                        wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        verwijderd_dp = True, 
                        datum_einde_garantie = '', 
                        ind_bevat_container = True, 
                        bag_hoofdadres_verblijfsobject_id = '', 
                        gbd_buurt_id = '', 
                        bag_openbareruimte_id = '', 
                        bag_nummeraanduiding_id = '', 
                        containerlocatie_type_naam = '', 
                        containerlocatie_id_nummer = '', 
                        containerlocatie_datum_wijziging = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        containerlocatie_opmerking = '', 
                        containerlocatie_end_of_life = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        containerlocatie_eigenaarschap = '', 
                        containerlocatie_eigenaarschap_opmerking = '', 
                        containerlocatie_type_artikelcode = '', 
                        bronadres = '', )
                    ]
            )
        else:
            return PaginatedHuishoudelijkafvalcontainerlocatieListEmbedded(
        )
        """

    def testPaginatedHuishoudelijkafvalcontainerlocatieListEmbedded(self):
        """Test PaginatedHuishoudelijkafvalcontainerlocatieListEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
