# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.api.loopafstand_categorie_v2_api import LoopafstandCategorieV2Api


class TestLoopafstandCategorieV2Api(unittest.IsolatedAsyncioTestCase):
    """LoopafstandCategorieV2Api unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = LoopafstandCategorieV2Api()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_huishoudelijkafval_loopafstand_categorie_v2_list2(self) -> None:
        """Test case for huishoudelijkafval_loopafstand_categorie_v2_list2

        """
        pass

    async def test_huishoudelijkafval_loopafstand_categorie_v2_retrieve2(self) -> None:
        """Test case for huishoudelijkafval_loopafstand_categorie_v2_retrieve2

        """
        pass


if __name__ == '__main__':
    unittest.main()
