# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalrolcontainer_melding_list import PaginatedHuishoudelijkafvalrolcontainerMeldingList

class TestPaginatedHuishoudelijkafvalrolcontainerMeldingList(unittest.TestCase):
    """PaginatedHuishoudelijkafvalrolcontainerMeldingList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalrolcontainerMeldingList:
        """Test PaginatedHuishoudelijkafvalrolcontainerMeldingList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalrolcontainerMeldingList`
        """
        model = PaginatedHuishoudelijkafvalrolcontainerMeldingList()
        if include_optional:
            return PaginatedHuishoudelijkafvalrolcontainerMeldingList(
                page = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list_page.PaginatedHuishoudelijkafvaladres_loopafstand_v2List_page(
                    number = 3, 
                    size = 20, 
                    total_elements = 5, 
                    total_pages = 3, ),
                links = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links(
                    self = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_self.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_self(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3', ), 
                    next = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_next.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_next(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=4', ), 
                    previous = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_previous.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_previous(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=2', ), ),
                embedded = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalrolcontainer_melding_list__embedded.PaginatedHuishoudelijkafvalrolcontainer_meldingList__embedded(
                    rolcontainer_melding = [
                        huishoudelijkafval_api_client.models.huishoudelijkafvalrolcontainer_melding.Huishoudelijkafvalrolcontainer_melding(
                            _links = null, 
                            id = -9223372036854775808, 
                            rolcontainer_id = -9223372036854775808, 
                            melding_type = '', 
                            afkomst_verzoek = '', 
                            soort_verzoek = '', 
                            aanmaakdatum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            wijzigingsdatum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            bag_verblijfsobject_id = '', 
                            bag_nummeraanduiding_id = '', )
                        ], )
            )
        else:
            return PaginatedHuishoudelijkafvalrolcontainerMeldingList(
        )
        """

    def testPaginatedHuishoudelijkafvalrolcontainerMeldingList(self):
        """Test PaginatedHuishoudelijkafvalrolcontainerMeldingList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
