# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalafvoermomenten_list_embedded import PaginatedHuishoudelijkafvalafvoermomentenListEmbedded

class TestPaginatedHuishoudelijkafvalafvoermomentenListEmbedded(unittest.TestCase):
    """PaginatedHuishoudelijkafvalafvoermomentenListEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalafvoermomentenListEmbedded:
        """Test PaginatedHuishoudelijkafvalafvoermomentenListEmbedded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalafvoermomentenListEmbedded`
        """
        model = PaginatedHuishoudelijkafvalafvoermomentenListEmbedded()
        if include_optional:
            return PaginatedHuishoudelijkafvalafvoermomentenListEmbedded(
                afvoermomenten = [
                    huishoudelijkafval_api_client.models.huishoudelijkafvalafvoermomenten.Huishoudelijkafvalafvoermomenten(
                        _links = null, 
                        id = '', 
                        verwerker = '', 
                        bon_nummer = '', 
                        datum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        tijd = '', 
                        ontvangst_locatie = '', 
                        afvalstroom_nummer = '', 
                        aanbieder = '', 
                        aanbieder_standplaats = '', 
                        aanbieder_standplaats_omschrijving = '', 
                        aanbieder_adres = '', 
                        aanbieder_postcode = '', 
                        aanbieder_plaatsnaam = '', 
                        afval_soort = '', 
                        geaccepteerd = '', 
                        opmerking = '', 
                        kenteken = '', 
                        kenteken_kort = '', 
                        weeg_bon = '', 
                        weeg_datum = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        weeg_tijdstip = '', 
                        inweging = -9223372036854775808, 
                        uitweging = -9223372036854775808, 
                        netto_gewicht = '', 
                        afvalstof_code = '', 
                        afvalstof_omschrijving = '', )
                    ]
            )
        else:
            return PaginatedHuishoudelijkafvalafvoermomentenListEmbedded(
        )
        """

    def testPaginatedHuishoudelijkafvalafvoermomentenListEmbedded(self):
        """Test PaginatedHuishoudelijkafvalafvoermomentenListEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
