# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalrolcontainer_actie import HuishoudelijkafvalrolcontainerActie

class TestHuishoudelijkafvalrolcontainerActie(unittest.TestCase):
    """HuishoudelijkafvalrolcontainerActie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HuishoudelijkafvalrolcontainerActie:
        """Test HuishoudelijkafvalrolcontainerActie
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HuishoudelijkafvalrolcontainerActie`
        """
        model = HuishoudelijkafvalrolcontainerActie()
        if include_optional:
            return HuishoudelijkafvalrolcontainerActie(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_rolcontainer_actie_links.HuishoudelijkafvaldefaultRolcontainerActieLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalrolcontainer_actie_link.Huishoudelijkafvalrolcontainer_actieLink(
                        href = '', 
                        title = '', 
                        id = -9223372036854775808, ), 
                    rolcontainer = huishoudelijkafval_api_client.models.huishoudelijkafvalrolcontainer_link.HuishoudelijkafvalrolcontainerLink(
                        href = '', 
                        title = '', 
                        id = -9223372036854775808, ), 
                    bag_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = -9223372036854775808,
                rolcontainer_id = -9223372036854775808,
                actie_type_code = '',
                actie_type_naam = '',
                interventie_datum = '',
                status = '',
                ronde = '',
                bezoek = -9223372036854775808,
                afkomst_verzoek = '',
                soort_verzoek = '',
                team = '',
                chip_nummer = '',
                soort_container = '',
                aanmaakdatum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                wijzigingsdatum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                bag_verblijfsobject_id = '',
                bag_nummeraanduiding_id = ''
            )
        else:
            return HuishoudelijkafvalrolcontainerActie(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_rolcontainer_actie_links.HuishoudelijkafvaldefaultRolcontainerActieLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalrolcontainer_actie_link.Huishoudelijkafvalrolcontainer_actieLink(
                        href = '', 
                        title = '', 
                        id = -9223372036854775808, ), 
                    rolcontainer = huishoudelijkafval_api_client.models.huishoudelijkafvalrolcontainer_link.HuishoudelijkafvalrolcontainerLink(
                        href = '', 
                        title = '', 
                        id = -9223372036854775808, ), 
                    bag_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = -9223372036854775808,
                rolcontainer_id = -9223372036854775808,
                bag_verblijfsobject_id = '',
                bag_nummeraanduiding_id = '',
        )
        """

    def testHuishoudelijkafvalrolcontainerActie(self):
        """Test HuishoudelijkafvalrolcontainerActie"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
