# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalticket_list import PaginatedHuishoudelijkafvalticketList

class TestPaginatedHuishoudelijkafvalticketList(unittest.TestCase):
    """PaginatedHuishoudelijkafvalticketList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalticketList:
        """Test PaginatedHuishoudelijkafvalticketList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalticketList`
        """
        model = PaginatedHuishoudelijkafvalticketList()
        if include_optional:
            return PaginatedHuishoudelijkafvalticketList(
                page = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list_page.PaginatedHuishoudelijkafvaladres_loopafstand_v2List_page(
                    number = 3, 
                    size = 20, 
                    total_elements = 5, 
                    total_pages = 3, ),
                links = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links(
                    self = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_self.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_self(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3', ), 
                    next = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_next.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_next(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=4', ), 
                    previous = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_previous.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_previous(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=2', ), ),
                embedded = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalticket_list__embedded.PaginatedHuishoudelijkafvalticketList__embedded(
                    ticket = [
                        huishoudelijkafval_api_client.models.huishoudelijkafvalticket.Huishoudelijkafvalticket(
                            _links = null, 
                            id = -9223372036854775808, 
                            container_id = '', 
                            containerlocatie_id = '', 
                            datum_creatie = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_factuur = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            factuur_nummer = '', 
                            datum_wijziging = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            referentienummer_leverancier = '', 
                            prioriteit_opmerking = '', 
                            prioriteit_naam = '', 
                            prioriteit_responstijd = -9223372036854775808, 
                            probleem_module_naam = [
                                ''
                                ], 
                            probleem = [
                                ''
                                ], 
                            oorzaak = [
                                ''
                                ], 
                            oplossing = [
                                ''
                                ], 
                            onderhoudsbedrijf = '', 
                            eigenaar = '', 
                            ticketstatus = '', 
                            tickettype = '', 
                            rangorde_nummer_tickettype = -9223372036854775808, 
                            datum_workflow_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_geaccepteerd = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_offerte = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_gepland = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_gereed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_afgerond = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_technische_goedkeuring = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_financiele_goedkeuring = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_gefactureerd = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            datum_afgewezen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            reden_afgewezen = '', 
                            prijs = 1.337, 
                            prijs_offerte = 1.337, 
                            doorlooptijd = '', 
                            items_definitief = '', 
                            items_offerte = '', 
                            gbd_buurt_id = '', 
                            gbd_buurt_naam = '', 
                            gbd_buurt_volgnummer = -9223372036854775808, 
                            gbd_buurt_code = '', 
                            gbd_wijk_id = '', 
                            gbd_wijk_naam = '', 
                            gbd_wijk_volgnummer = -9223372036854775808, 
                            gbd_stadsdeel_id = '', 
                            gbd_stadsdeel_naam = '', 
                            gbd_stadsdeel_volgnummer = -9223372036854775808, 
                            gbd_ggw_id = '', 
                            gbd_ggw_naam = '', 
                            gbd_ggw_volgnummer = '', )
                        ], )
            )
        else:
            return PaginatedHuishoudelijkafvalticketList(
        )
        """

    def testPaginatedHuishoudelijkafvalticketList(self):
        """Test PaginatedHuishoudelijkafvalticketList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
