# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list import PaginatedHuishoudelijkafvaladresLoopafstandV2List

class TestPaginatedHuishoudelijkafvaladresLoopafstandV2List(unittest.TestCase):
    """PaginatedHuishoudelijkafvaladresLoopafstandV2List unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvaladresLoopafstandV2List:
        """Test PaginatedHuishoudelijkafvaladresLoopafstandV2List
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvaladresLoopafstandV2List`
        """
        model = PaginatedHuishoudelijkafvaladresLoopafstandV2List()
        if include_optional:
            return PaginatedHuishoudelijkafvaladresLoopafstandV2List(
                page = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list_page.PaginatedHuishoudelijkafvaladres_loopafstand_v2List_page(
                    number = 3, 
                    size = 20, 
                    total_elements = 5, 
                    total_pages = 3, ),
                links = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links(
                    self = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_self.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_self(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3', ), 
                    next = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_next.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_next(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=4', ), 
                    previous = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_previous.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_previous(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=2', ), ),
                embedded = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__embedded.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__embedded(
                    adres_loopafstand_v2 = [
                        huishoudelijkafval_api_client.models.huishoudelijkafvaladres_loopafstand_v2.Huishoudelijkafvaladres_loopafstand_v2(
                            _links = null, 
                            id = '', 
                            adresseerbaarobject_id = '', 
                            adresseerbaarobject_type = '', 
                            nummeraanduiding_id = '', 
                            gebruiksdoel = '', 
                            cluster_id = '', 
                            fractie = '', 
                            fractie_omschrijving = '', 
                            loopafstand_categorie_id = '', 
                            loopafstand = 1.337, 
                            geometrie = huishoudelijkafval_api_client.models.point.Point(), 
                            wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            verwijderd_dp = True, )
                        ], )
            )
        else:
            return PaginatedHuishoudelijkafvaladresLoopafstandV2List(
        )
        """

    def testPaginatedHuishoudelijkafvaladresLoopafstandV2List(self):
        """Test PaginatedHuishoudelijkafvaladresLoopafstandV2List"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
