# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalservicegebieden_list import PaginatedHuishoudelijkafvalservicegebiedenList

class TestPaginatedHuishoudelijkafvalservicegebiedenList(unittest.TestCase):
    """PaginatedHuishoudelijkafvalservicegebiedenList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalservicegebiedenList:
        """Test PaginatedHuishoudelijkafvalservicegebiedenList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalservicegebiedenList`
        """
        model = PaginatedHuishoudelijkafvalservicegebiedenList()
        if include_optional:
            return PaginatedHuishoudelijkafvalservicegebiedenList(
                page = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list_page.PaginatedHuishoudelijkafvaladres_loopafstand_v2List_page(
                    number = 3, 
                    size = 20, 
                    total_elements = 5, 
                    total_pages = 3, ),
                links = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links(
                    self = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_self.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_self(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3', ), 
                    next = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_next.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_next(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=4', ), 
                    previous = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list__links_previous.PaginatedHuishoudelijkafvaladres_loopafstand_v2List__links_previous(
                        href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=2', ), ),
                embedded = huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalservicegebieden_list__embedded.PaginatedHuishoudelijkafvalservicegebiedenList__embedded(
                    servicegebieden = [
                        huishoudelijkafval_api_client.models.huishoudelijkafvalservicegebieden.Huishoudelijkafvalservicegebieden(
                            _links = null, 
                            id = '', 
                            bag_object_id = '', 
                            bag_object_type = '', 
                            servicegebieden_locatie_id = '', 
                            fractie_code = '', 
                            fractie_omschrijving = '', 
                            loopafstand_categorie_id = '', 
                            loopafstand_categorie_omschrijving = '', 
                            loopafstand_categorie_vanaf = 1.337, 
                            loopafstand_categorie_tot = 1.337, 
                            categorie_wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            categorie_verwijderd_dp = True, 
                            geometrie = huishoudelijkafval_api_client.models.polygon.Polygon(), )
                        ], )
            )
        else:
            return PaginatedHuishoudelijkafvalservicegebiedenList(
        )
        """

    def testPaginatedHuishoudelijkafvalservicegebiedenList(self):
        """Test PaginatedHuishoudelijkafvalservicegebiedenList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
