# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list_links_self import PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf

class TestPaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf(unittest.TestCase):
    """PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf:
        """Test PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf`
        """
        model = PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf()
        if include_optional:
            return PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf(
                href = 'https://api.data.amsterdam.nl/v1/.../resource/?page=3'
            )
        else:
            return PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf(
        )
        """

    def testPaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf(self):
        """Test PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinksSelf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
