# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalticket import Huishoudelijkafvalticket

class TestHuishoudelijkafvalticket(unittest.TestCase):
    """Huishoudelijkafvalticket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Huishoudelijkafvalticket:
        """Test Huishoudelijkafvalticket
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Huishoudelijkafvalticket`
        """
        model = Huishoudelijkafvalticket()
        if include_optional:
            return Huishoudelijkafvalticket(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_ticket_links.HuishoudelijkafvaldefaultTicketLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalticket_link.HuishoudelijkafvalticketLink(
                        href = '', 
                        title = '', 
                        id = -9223372036854775808, ), 
                    container = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainer_link.HuishoudelijkafvalcontainerLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    containerlocatie = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainerlocatie_link.HuishoudelijkafvalcontainerlocatieLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_wijk = huishoudelijkafval_api_client.models.gebieden_wijken_raw_identifier.GebiedenWijkenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_stadsdeel = huishoudelijkafval_api_client.models.gebieden_stadsdelen_raw_identifier.GebiedenStadsdelenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_ggw = huishoudelijkafval_api_client.models.gebieden_ggwgebieden_raw_identifier.GebiedenGgwgebiedenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = -9223372036854775808,
                container_id = '',
                containerlocatie_id = '',
                datum_creatie = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_factuur = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                factuur_nummer = '',
                datum_wijziging = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                referentienummer_leverancier = '',
                prioriteit_opmerking = '',
                prioriteit_naam = '',
                prioriteit_responstijd = -9223372036854775808,
                probleem_module_naam = [
                    ''
                    ],
                probleem = [
                    ''
                    ],
                oorzaak = [
                    ''
                    ],
                oplossing = [
                    ''
                    ],
                onderhoudsbedrijf = '',
                eigenaar = '',
                ticketstatus = '',
                tickettype = '',
                rangorde_nummer_tickettype = -9223372036854775808,
                datum_workflow_start = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_geaccepteerd = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_offerte = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_gepland = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_gereed = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_afgerond = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_technische_goedkeuring = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_financiele_goedkeuring = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_gefactureerd = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_afgewezen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                reden_afgewezen = '',
                prijs = 1.337,
                prijs_offerte = 1.337,
                doorlooptijd = '',
                items_definitief = '',
                items_offerte = '',
                gbd_buurt_id = '',
                gbd_buurt_naam = '',
                gbd_buurt_volgnummer = -9223372036854775808,
                gbd_buurt_code = '',
                gbd_wijk_id = '',
                gbd_wijk_naam = '',
                gbd_wijk_volgnummer = -9223372036854775808,
                gbd_stadsdeel_id = '',
                gbd_stadsdeel_naam = '',
                gbd_stadsdeel_volgnummer = -9223372036854775808,
                gbd_ggw_id = '',
                gbd_ggw_naam = '',
                gbd_ggw_volgnummer = ''
            )
        else:
            return Huishoudelijkafvalticket(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_ticket_links.HuishoudelijkafvaldefaultTicketLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalticket_link.HuishoudelijkafvalticketLink(
                        href = '', 
                        title = '', 
                        id = -9223372036854775808, ), 
                    container = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainer_link.HuishoudelijkafvalcontainerLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    containerlocatie = huishoudelijkafval_api_client.models.huishoudelijkafvalcontainerlocatie_link.HuishoudelijkafvalcontainerlocatieLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_wijk = huishoudelijkafval_api_client.models.gebieden_wijken_raw_identifier.GebiedenWijkenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_stadsdeel = huishoudelijkafval_api_client.models.gebieden_stadsdelen_raw_identifier.GebiedenStadsdelenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_ggw = huishoudelijkafval_api_client.models.gebieden_ggwgebieden_raw_identifier.GebiedenGgwgebiedenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = -9223372036854775808,
                container_id = '',
                containerlocatie_id = '',
                gbd_buurt_id = '',
                gbd_wijk_id = '',
                gbd_stadsdeel_id = '',
                gbd_ggw_id = '',
        )
        """

    def testHuishoudelijkafvalticket(self):
        """Test Huishoudelijkafvalticket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
