# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalplanning_voertuigen_list_embedded import PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded

class TestPaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded(unittest.TestCase):
    """PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded:
        """Test PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded`
        """
        model = PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded()
        if include_optional:
            return PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded(
                planning_voertuigen = [
                    huishoudelijkafval_api_client.models.huishoudelijkafvalplanning_voertuigen.Huishoudelijkafvalplanning_voertuigen(
                        _links = null, 
                        id = -9223372036854775808, 
                        soort_werkzaamheden = '', 
                        kenteken = '', 
                        kenteken_kort = '', 
                        categorie = '', 
                        activiteit = '', 
                        werkzaamheden_code = '', 
                        werkzaamheden_omschrijving = '', 
                        werkzaamheden_datum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        werkzaamheden_datum_ref_id = -9223372036854775808, 
                        werkzaamheden_starttijd = '', 
                        werkzaamheden_eindtijd = '', 
                        werkzaamheden_uren_gepland = 1.337, 
                        pauze_starttijd = '', 
                        pauze_eindtijd = '', 
                        pauze_uren_gepland = 1.337, 
                        fase = '', 
                        memo = '', 
                        team = '', 
                        voertuig_inhuur_indicatie = '', 
                        aantal_medewerkers = 1.337, 
                        aantal_medewerkers_intern = 1.337, 
                        aantal_medewerkers_inhuur = 1.337, 
                        uren_inzet_medewerker_intern = 1.337, 
                        uren_inzet_medewerker_inhuur = 1.337, 
                        uren_inzet_voertuig = 1.337, 
                        datum_verwerkt_stadsdelen = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        datum_aanwezig_bron = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ]
            )
        else:
            return PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded(
        )
        """

    def testPaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded(self):
        """Test PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
