# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalclusterfractie import Huishoudelijkafvalclusterfractie

class TestHuishoudelijkafvalclusterfractie(unittest.TestCase):
    """Huishoudelijkafvalclusterfractie unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Huishoudelijkafvalclusterfractie:
        """Test Huishoudelijkafvalclusterfractie
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Huishoudelijkafvalclusterfractie`
        """
        model = Huishoudelijkafvalclusterfractie()
        if include_optional:
            return Huishoudelijkafvalclusterfractie(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_clusterfractie_links.HuishoudelijkafvaldefaultClusterfractieLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalclusterfractie_link.HuishoudelijkafvalclusterfractieLink(
                        href = '', 
                        title = '', 
                        id = '', ), ),
                id = '',
                cluster_id = '',
                aantal_containers = -9223372036854775808,
                volume_m3 = 1.337,
                code = '',
                omschrijving = '',
                datum_opvoer = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                datum_einde = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verwijderd_dp = True
            )
        else:
            return Huishoudelijkafvalclusterfractie(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_clusterfractie_links.HuishoudelijkafvaldefaultClusterfractieLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalclusterfractie_link.HuishoudelijkafvalclusterfractieLink(
                        href = '', 
                        title = '', 
                        id = '', ), ),
                id = '',
        )
        """

    def testHuishoudelijkafvalclusterfractie(self):
        """Test Huishoudelijkafvalclusterfractie"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
