# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.gebieden_wijken_raw_identifier import GebiedenWijkenRawIdentifier

class TestGebiedenWijkenRawIdentifier(unittest.TestCase):
    """GebiedenWijkenRawIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GebiedenWijkenRawIdentifier:
        """Test GebiedenWijkenRawIdentifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GebiedenWijkenRawIdentifier`
        """
        model = GebiedenWijkenRawIdentifier()
        if include_optional:
            return GebiedenWijkenRawIdentifier(
                href = '',
                title = '',
                identificatie = ''
            )
        else:
            return GebiedenWijkenRawIdentifier(
                href = '',
                title = '',
                identificatie = '',
        )
        """

    def testGebiedenWijkenRawIdentifier(self):
        """Test GebiedenWijkenRawIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
