# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.huishoudelijkafvalweging import Huishoudelijkafvalweging

class TestHuishoudelijkafvalweging(unittest.TestCase):
    """Huishoudelijkafvalweging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Huishoudelijkafvalweging:
        """Test Huishoudelijkafvalweging
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Huishoudelijkafvalweging`
        """
        model = Huishoudelijkafvalweging()
        if include_optional:
            return Huishoudelijkafvalweging(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvalv1_weging_links.Huishoudelijkafvalv1WegingLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalweging_link.HuishoudelijkafvalwegingLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    bag_hoofdadres_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                cluster_id = '',
                cluster_subcluster_indicatie = True,
                weegsysteem_id = -9223372036854775808,
                weegsysteem_omschrijving = '',
                volgnummer = -9223372036854775808,
                datum_weging = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                tijdstip_weging = '',
                locatienummer = '',
                fractie_code = -9223372036854775808,
                fractie_omschrijving = '',
                eerste_weging = 1.337,
                tweede_weging = 1.337,
                netto_gewicht = 1.337,
                geometrie = huishoudelijkafval_api_client.models.point.Point(),
                bediening_code = -9223372036854775808,
                bediening_omschrijving = '',
                wijzigingsdatum_dp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                verwijderd_dp = True,
                bag_hoofdadres_verblijfsobject_id = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_nummeraanduiding_id = '',
                weging_kenteken = ''
            )
        else:
            return Huishoudelijkafvalweging(
                links = huishoudelijkafval_api_client.models.huishoudelijkafvalv1_weging_links.Huishoudelijkafvalv1WegingLinks(
                    schema = '', 
                    self = huishoudelijkafval_api_client.models.huishoudelijkafvalweging_link.HuishoudelijkafvalwegingLink(
                        href = '', 
                        title = '', 
                        id = '', ), 
                    bag_hoofdadres_verblijfsobject = huishoudelijkafval_api_client.models.bag_verblijfsobjecten_raw_identifier.BagVerblijfsobjectenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    gbd_buurt = huishoudelijkafval_api_client.models.gebieden_buurten_raw_identifier.GebiedenBuurtenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_openbareruimte = huishoudelijkafval_api_client.models.bag_openbareruimtes_raw_identifier.BagOpenbareruimtesRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), 
                    bag_nummeraanduiding = huishoudelijkafval_api_client.models.bag_nummeraanduidingen_raw_identifier.BagNummeraanduidingenRawIdentifier(
                        href = '', 
                        title = '', 
                        identificatie = '', ), ),
                id = '',
                bag_hoofdadres_verblijfsobject_id = '',
                gbd_buurt_id = '',
                bag_openbareruimte_id = '',
                bag_nummeraanduiding_id = '',
        )
        """

    def testHuishoudelijkafvalweging(self):
        """Test Huishoudelijkafvalweging"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
