# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalrolcontainer_list_embedded import PaginatedHuishoudelijkafvalrolcontainerListEmbedded

class TestPaginatedHuishoudelijkafvalrolcontainerListEmbedded(unittest.TestCase):
    """PaginatedHuishoudelijkafvalrolcontainerListEmbedded unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaginatedHuishoudelijkafvalrolcontainerListEmbedded:
        """Test PaginatedHuishoudelijkafvalrolcontainerListEmbedded
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaginatedHuishoudelijkafvalrolcontainerListEmbedded`
        """
        model = PaginatedHuishoudelijkafvalrolcontainerListEmbedded()
        if include_optional:
            return PaginatedHuishoudelijkafvalrolcontainerListEmbedded(
                rolcontainer = [
                    huishoudelijkafval_api_client.models.huishoudelijkafvalrolcontainer.Huishoudelijkafvalrolcontainer(
                        _links = null, 
                        id = -9223372036854775808, 
                        fractie_omschrijving = '', 
                        chip_nummer = '', 
                        chip_type = '', 
                        heeft_chip_sinds = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        barcode = '', 
                        heeft_barcode_sinds = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        status = '', 
                        status_sinds = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        aanmaakdatum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        wijzigingsdatum = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        soort_container = '', 
                        straatnaam = '', 
                        huisnummer = -9223372036854775808, 
                        huisletter = '', 
                        huisnummertoevoeging = '', 
                        postcode = '', 
                        woonplaats_naam = '', 
                        geometrie = huishoudelijkafval_api_client.models.point.Point(), 
                        typeadresseerbaarobject = '', 
                        gebruiksdoel = '', 
                        bag_woonplaats_id = '', 
                        bag_openbareruimte_id = '', 
                        bag_verblijfsobject_id = '', 
                        bag_nummeraanduiding_id = '', 
                        gebied_buurt_naam = '', 
                        gebied_buurt_code = '', 
                        gebied_buurt_id = '', 
                        gebied_wijk_naam = '', 
                        gebied_wijk_code = '', 
                        gebied_wijk_id = '', 
                        gebied_stadsdeel_naam = '', 
                        gebied_stadsdeel_code = '', 
                        gebied_stadsdeel_id = '', 
                        gebied_ggw_naam = '', 
                        gebied_ggw_code = '', 
                        gebied_ggw_id = '', )
                    ]
            )
        else:
            return PaginatedHuishoudelijkafvalrolcontainerListEmbedded(
        )
        """

    def testPaginatedHuishoudelijkafvalrolcontainerListEmbedded(self):
        """Test PaginatedHuishoudelijkafvalrolcontainerListEmbedded"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
