services:
  openapi-generator-cli:
    image: openapitools/openapi-generator-cli:v7.14.0
    command:
      - "generate"
      - "-i"
      - "https://api.data.amsterdam.nl/v1/huishoudelijkafval/openapi.json"
      - "-g"
      - "python"
      - "-o"
      - "/local"
      - "--package-name"
      - "huishoudelijkafval_api_client"
      - "--git-host"
      - "github.com"
      - "--git-user-id"
      - "Amsterdam"
      - "--git-repo-id"
      - "huishoudelijkafval-api-client"
      - "--library"
      - "asyncio"
    volumes:
      - ".:/local"

  huishoudelijkafval-api-client:
    image: amsterdam/huishoudelijkafval-api-client
    build:
      context: .
    volumes:
      - ".:/opt/huishoudelijkafval-api-client"
