# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from huishoudelijkafval_api_client.models.huishoudelijkafvaldefault_adres_loopafstand_v2_links import HuishoudelijkafvaldefaultAdresLoopafstandV2Links
from huishoudelijkafval_api_client.models.point import Point
from typing import Optional, Set
from typing_extensions import Self

class HuishoudelijkafvaladresLoopafstandV2(BaseModel):
    """
    adresLoopafstandV2
    """ # noqa: E501
    links: HuishoudelijkafvaldefaultAdresLoopafstandV2Links = Field(alias="_links")
    id: Annotated[str, Field(strict=True, max_length=2147483647)] = Field(description="Uniek identificerend kenmerk van het record")
    adresseerbaarobject_id: Optional[Annotated[str, Field(strict=True, max_length=2147483647)]] = Field(default=None, description="Uniek identificerend kenmerk van adresseerbaarobject", alias="adresseerbaarobjectId")
    adresseerbaarobject_type: Optional[Annotated[str, Field(strict=True, max_length=2147483647)]] = Field(default=None, description="Typering adresseerbaar object conform BAG: verblijfsobject, ligplaats , standplaats", alias="adresseerbaarobjectType")
    nummeraanduiding_id: Optional[Annotated[str, Field(strict=True, max_length=2147483647)]] = Field(default=None, description="BAG:Landelijke identificatie nummeraanduiding", alias="nummeraanduidingId")
    gebruiksdoel: Optional[Annotated[str, Field(strict=True, max_length=2147483647)]] = Field(default=None, description="BAG:Een categorisering van de gebruiksdoelen van het betreffende verblijfsobject, ligplaats en standplaatsen zoals dit door de overheid als zodanig is toegestaan")
    cluster_id: Optional[StrictStr] = Field(description="Uniek identificerend kenmerk van cluster waarnaar de afstand is berekend", alias="clusterId")
    fractie: Optional[Annotated[str, Field(strict=True, max_length=2147483647)]] = Field(default=None, description="Code afvalfractie waarnaar de afstand is bepaald")
    fractie_omschrijving: Optional[Annotated[str, Field(strict=True, max_length=2147483647)]] = Field(default=None, description="Omschrijving afvalfractie waarnaar de afstand is bepaald", alias="fractieOmschrijving")
    loopafstand_categorie_id: Optional[StrictStr] = Field(description="Relatie naar de categorie waarin de berekende loopafstand valt", alias="loopafstandCategorieId")
    loopafstand: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Berekende afstand over de weg in meter  van woning tot cluster van containers van de betreffende afvalfractie")
    geometrie: Optional[Point] = None
    wijzigingsdatum_dp: Optional[datetime] = Field(default=None, description="Datum waarop het object is gewijzigd", alias="wijzigingsdatumDp")
    verwijderd_dp: Optional[StrictBool] = Field(default=None, description="Indicatie of het object verwijderd is in de datapijplijn", alias="verwijderdDp")
    __properties: ClassVar[List[str]] = ["_links", "id", "adresseerbaarobjectId", "adresseerbaarobjectType", "nummeraanduidingId", "gebruiksdoel", "clusterId", "fractie", "fractieOmschrijving", "loopafstandCategorieId", "loopafstand", "geometrie", "wijzigingsdatumDp", "verwijderdDp"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of HuishoudelijkafvaladresLoopafstandV2 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "cluster_id",
            "loopafstand_categorie_id",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of geometrie
        if self.geometrie:
            _dict['geometrie'] = self.geometrie.to_dict()
        # set to None if adresseerbaarobject_id (nullable) is None
        # and model_fields_set contains the field
        if self.adresseerbaarobject_id is None and "adresseerbaarobject_id" in self.model_fields_set:
            _dict['adresseerbaarobjectId'] = None

        # set to None if adresseerbaarobject_type (nullable) is None
        # and model_fields_set contains the field
        if self.adresseerbaarobject_type is None and "adresseerbaarobject_type" in self.model_fields_set:
            _dict['adresseerbaarobjectType'] = None

        # set to None if nummeraanduiding_id (nullable) is None
        # and model_fields_set contains the field
        if self.nummeraanduiding_id is None and "nummeraanduiding_id" in self.model_fields_set:
            _dict['nummeraanduidingId'] = None

        # set to None if gebruiksdoel (nullable) is None
        # and model_fields_set contains the field
        if self.gebruiksdoel is None and "gebruiksdoel" in self.model_fields_set:
            _dict['gebruiksdoel'] = None

        # set to None if cluster_id (nullable) is None
        # and model_fields_set contains the field
        if self.cluster_id is None and "cluster_id" in self.model_fields_set:
            _dict['clusterId'] = None

        # set to None if fractie (nullable) is None
        # and model_fields_set contains the field
        if self.fractie is None and "fractie" in self.model_fields_set:
            _dict['fractie'] = None

        # set to None if fractie_omschrijving (nullable) is None
        # and model_fields_set contains the field
        if self.fractie_omschrijving is None and "fractie_omschrijving" in self.model_fields_set:
            _dict['fractieOmschrijving'] = None

        # set to None if loopafstand_categorie_id (nullable) is None
        # and model_fields_set contains the field
        if self.loopafstand_categorie_id is None and "loopafstand_categorie_id" in self.model_fields_set:
            _dict['loopafstandCategorieId'] = None

        # set to None if loopafstand (nullable) is None
        # and model_fields_set contains the field
        if self.loopafstand is None and "loopafstand" in self.model_fields_set:
            _dict['loopafstand'] = None

        # set to None if wijzigingsdatum_dp (nullable) is None
        # and model_fields_set contains the field
        if self.wijzigingsdatum_dp is None and "wijzigingsdatum_dp" in self.model_fields_set:
            _dict['wijzigingsdatumDp'] = None

        # set to None if verwijderd_dp (nullable) is None
        # and model_fields_set contains the field
        if self.verwijderd_dp is None and "verwijderd_dp" in self.model_fields_set:
            _dict['verwijderdDp'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HuishoudelijkafvaladresLoopafstandV2 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "_links": HuishoudelijkafvaldefaultAdresLoopafstandV2Links.from_dict(obj["_links"]) if obj.get("_links") is not None else None,
            "id": obj.get("id"),
            "adresseerbaarobjectId": obj.get("adresseerbaarobjectId"),
            "adresseerbaarobjectType": obj.get("adresseerbaarobjectType"),
            "nummeraanduidingId": obj.get("nummeraanduidingId"),
            "gebruiksdoel": obj.get("gebruiksdoel"),
            "clusterId": obj.get("clusterId"),
            "fractie": obj.get("fractie"),
            "fractieOmschrijving": obj.get("fractieOmschrijving"),
            "loopafstandCategorieId": obj.get("loopafstandCategorieId"),
            "loopafstand": obj.get("loopafstand"),
            "geometrie": Point.from_dict(obj["geometrie"]) if obj.get("geometrie") is not None else None,
            "wijzigingsdatumDp": obj.get("wijzigingsdatumDp"),
            "verwijderdDp": obj.get("verwijderdDp")
        })
        return _obj


