# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list_links import PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinks
from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvaladres_loopafstand_v2_list_page import PaginatedHuishoudelijkafvaladresLoopafstandV2ListPage
from huishoudelijkafval_api_client.models.paginated_huishoudelijkafvalplanning_voertuigen_list_embedded import PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded
from typing import Optional, Set
from typing_extensions import Self

class PaginatedHuishoudelijkafvalplanningVoertuigenList(BaseModel):
    """
    PaginatedHuishoudelijkafvalplanningVoertuigenList
    """ # noqa: E501
    page: Optional[PaginatedHuishoudelijkafvaladresLoopafstandV2ListPage] = None
    links: Optional[PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinks] = Field(default=None, alias="_links")
    embedded: Optional[PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded] = Field(default=None, alias="_embedded")
    __properties: ClassVar[List[str]] = ["page", "_links", "_embedded"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaginatedHuishoudelijkafvalplanningVoertuigenList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of page
        if self.page:
            _dict['page'] = self.page.to_dict()
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of embedded
        if self.embedded:
            _dict['_embedded'] = self.embedded.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaginatedHuishoudelijkafvalplanningVoertuigenList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "page": PaginatedHuishoudelijkafvaladresLoopafstandV2ListPage.from_dict(obj["page"]) if obj.get("page") is not None else None,
            "_links": PaginatedHuishoudelijkafvaladresLoopafstandV2ListLinks.from_dict(obj["_links"]) if obj.get("_links") is not None else None,
            "_embedded": PaginatedHuishoudelijkafvalplanningVoertuigenListEmbedded.from_dict(obj["_embedded"]) if obj.get("_embedded") is not None else None
        })
        return _obj


