# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from huishoudelijkafval_api_client.models.huishoudelijkafvalservicegebieden_locatie import HuishoudelijkafvalservicegebiedenLocatie
from typing import Optional, Set
from typing_extensions import Self

class PaginatedHuishoudelijkafvalservicegebiedenLocatieListEmbedded(BaseModel):
    """
    PaginatedHuishoudelijkafvalservicegebiedenLocatieListEmbedded
    """ # noqa: E501
    servicegebieden_locatie: Optional[List[HuishoudelijkafvalservicegebiedenLocatie]] = None
    __properties: ClassVar[List[str]] = ["servicegebieden_locatie"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaginatedHuishoudelijkafvalservicegebiedenLocatieListEmbedded from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in servicegebieden_locatie (list)
        _items = []
        if self.servicegebieden_locatie:
            for _item_servicegebieden_locatie in self.servicegebieden_locatie:
                if _item_servicegebieden_locatie:
                    _items.append(_item_servicegebieden_locatie.to_dict())
            _dict['servicegebieden_locatie'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaginatedHuishoudelijkafvalservicegebiedenLocatieListEmbedded from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "servicegebieden_locatie": [HuishoudelijkafvalservicegebiedenLocatie.from_dict(_item) for _item in obj["servicegebieden_locatie"]] if obj.get("servicegebieden_locatie") is not None else None
        })
        return _obj


