# coding: utf-8

"""
    Afvalcontainers, putten en weeggegevens

    Alle locaties van afvalcontainers (ondergrondse afvalcontainers, bovengrondse afvalcontainers en rolcontainers) en  betonputten van de Gemeente Amsterdam. De locaties worden dagelijks bijgewerkt en bevatten de fracties Rest, Papier, Glas en Textiel. Naast de objectinformatie zijn ook de weeggegevens beschikbaar.

    The version of the OpenAPI document: 2.5.0
    Contact: datapunt@amsterdam.nl
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List, Optional
from huishoudelijkafval_api_client.models.huishoudelijkafvalrolcontainer_actie import HuishoudelijkafvalrolcontainerActie
from typing import Optional, Set
from typing_extensions import Self

class PaginatedHuishoudelijkafvalrolcontainerActieListEmbedded(BaseModel):
    """
    PaginatedHuishoudelijkafvalrolcontainerActieListEmbedded
    """ # noqa: E501
    rolcontainer_actie: Optional[List[HuishoudelijkafvalrolcontainerActie]] = None
    __properties: ClassVar[List[str]] = ["rolcontainer_actie"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaginatedHuishoudelijkafvalrolcontainerActieListEmbedded from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in rolcontainer_actie (list)
        _items = []
        if self.rolcontainer_actie:
            for _item_rolcontainer_actie in self.rolcontainer_actie:
                if _item_rolcontainer_actie:
                    _items.append(_item_rolcontainer_actie.to_dict())
            _dict['rolcontainer_actie'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaginatedHuishoudelijkafvalrolcontainerActieListEmbedded from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "rolcontainer_actie": [HuishoudelijkafvalrolcontainerActie.from_dict(_item) for _item in obj["rolcontainer_actie"]] if obj.get("rolcontainer_actie") is not None else None
        })
        return _obj


